baseURL = "https://sushpants.github.io/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Sushpants"
theme = "hallo"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]

[Author]
    name = "Hallo"

[params]

    [[params.links]]
        iconset = "youtube"
        icon = "youtube"
        title = "youtube"
        url = "https://youtube.com/sushpants"

    [[params.links]]
        icon = "github"
        title = "Github"
        url = "https://github.com/"

    [[params.links]]
        icon = "instagram"
        title = "instagram"
        url = "https://instagram.com"
